# Generated by Django 5.2.7 on 2025-10-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_consulta_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='indicaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
